### ISSUE TITLE
Decide on profile fields and copy 

### ISSUE THREAD

**Issue by developess** [fac-14/sleuth-coop#25]
Hi @Hilary-Simpson 

Here is the spreadsheet we discussed with the options/fields that SMEs can add. This is based on our conversation and things you mentioned that are useful. 

It would be great if you or Ellie could look through and amend or add things as you see fit (change questions, add helper text or recategorise things).

Link:
https://docs.google.com/spreadsheets/d/1N4_TQGf8gJEn_xgrzdqgkNNYExFwB9WbAu4N3PSM8sE/edit?usp=sharing

I will probably create another spreadsheet for copy on the site so you can check that.

Comment below when you're happy with it!

**Comment by Hilary-Simpson** [comment]
Yes its done now
