### ISSUE TITLE
Create Style Guide and Scss for home, info and profile

### ISSUE THREAD

**Issue by developess** [fac-14/sleuth-coop#31]
These were the pages created in #2 #3 #6 

- [x] Should use Sass variables for colours, fonts, shadows etc
- [x] Should use labelling and nested selectors to keep the file organised

**Comment by VirtualDOMinic** [comment]
Update: we had a group discussion and decided to go with "standard" Sass, not styled components for now!

SC look interesting, but we've got time constraints!
