### ISSUE TITLE
Bits 'n Pieces

### ISSUE THREAD

**Issue by developess** [fac-14/sleuth-coop#47]
**Landing Page**
- [x] Can we vertically align the stuff on the home screen, it's sitting high on the window at the moment

**Carousel**
- [x] Link the Submit button on carousel to `profile/123` for demonstration purposes

**Profile**
- [x]  The heading tabs that project out from the sidebar. Can we round the ends of these so they are circular? I also wonder whether it would look better with a bit more left padding on the text?
- [x] White cards / question fields: I think they should be a bit narrower so there's more empty space to the left and right. I also think some more spacing between the first white card and the section header would be good. 
- [x] Could we flex the section containers so if there's only 1 short one it sits centrally in the section area?
- [x] Add an actual logo image for Senzing
- [x] Hover animation on header links - can we transition this so it looks smoother and also round the ends of the border to circles. There looks to be 2 transitions happening at slightly different times - fix that.

**Comment by SleepySheepy172** [comment]
-[ ] Add a delete profile button only when in SME profile view
-[ ] show home button on SME profile view and show back button on gov profile view
