### ISSUE TITLE
Build UX/styles for basic profile input

### ISSUE THREAD

**Issue by developess** [fac-14/sleuth-coop#5]
Relates to User Story from issue #4

In technical terms this means:
- [x] Sliding form carousel style
- [x] Partially hidden previous/next question
- [x] Progress circles
- [x] Next / Previous arrows
- [x] Submit data
- [x] Store data on db

**Comment by VirtualDOMinic** [comment]
Carousel to do:
- [ ] Progress bar/circles
- [ ] Use "enter" (or arrow keys?) to move along carousel, but not on the very last bit
- [ ] Password entry?? Stretch goal/second sprint goal?
- [ ] Style submit button properly
- [ ] Disable (horizontal) dragging of text area
- [ ] Anything else?

Possible options for textarea:
``` 
textarea {
  resize: none;
  resize: vertical;
}
```
